-- Sound Effect Replacer 0.4.0
--
-- A content mod for Red, Blue, Yellow, Gold, Silver, and Crystal. Its player-facing
-- layout follows Easy Custom Music v2’s generation split:
--
--   assets/Gen 1/{General,Specific} Sound Effects/<target>/
--   assets/Gen 2/{General,Specific} Sound Effects/<target>/
--
-- The active game reads its matching tree. Every target folder can contain a
-- validated playlist; selection advances once each time the target is played.

return function(mod)
  local GameVersion = require("src.core.GameVersion")
  local ChipAsm = require("src.audio.ChipAsm")
  local Sound = require("src.core.Sound")
  local POTATO_VOXEL_MOD_ID = "potato_voxel"
  local POTATO_VOXEL_STARTUP_SFX = "SFX_SOUND_EFFECT_REPLACER_POTATO_VOXEL_DETECTED"
-- Generated by tools/build_catalog.py from current local Gen1Recomp manifests.
-- This file contains IDs only; it contains no ROM program/audio data.

local Catalog = {
  gen1_sfx = {
    "59",
    "Arrow_Tiles",
    "Ball_Poof",
    "Ball_Toss",
    "Battle_09",
    "Battle_0B",
    "Battle_0C",
    "Battle_0D",
    "Battle_0E",
    "Battle_0F",
    "Battle_12",
    "Battle_13",
    "Battle_14",
    "Battle_16",
    "Battle_17",
    "Battle_18",
    "Battle_19",
    "Battle_1B",
    "Battle_1C",
    "Battle_1E",
    "Battle_20",
    "Battle_21",
    "Battle_22",
    "Battle_23",
    "Battle_24",
    "Battle_25",
    "Battle_26",
    "Battle_27",
    "Battle_28",
    "Battle_29",
    "Battle_2A",
    "Battle_2B",
    "Battle_2C",
    "Battle_2E",
    "Battle_2F",
    "Battle_31",
    "Battle_32",
    "Battle_33",
    "Battle_34",
    "Battle_35",
    "Battle_36",
    "Caught_Mon",
    "Collision",
    "Cut",
    "Damage",
    "Denied",
    "Dex_Page_Added",
    "Doubleslap",
    "Enter_PC",
    "Faint_Fall",
    "Faint_Thud",
    "Fly",
    "Get_Item1",
    "Get_Item2",
    "Get_Key_Item",
    "Go_Inside",
    "Go_Outside",
    "Heal_Ailment",
    "Heal_HP",
    "Healing_Machine",
    "Horn_Drill",
    "Intro_Crash",
    "Intro_Hip",
    "Intro_Hop",
    "Intro_Lunge",
    "Intro_Raise",
    "Intro_Whoosh",
    "Ledge",
    "Level_Up",
    "Not_Very_Effective",
    "Peck",
    "Poisoned",
    "Pokedex_Rating",
    "Pokeflute",
    "Pound",
    "Press_AB",
    "Psybeam",
    "Psychic_M",
    "Purchase",
    "Push_Boulder",
    "Run",
    "SS_Anne_Horn",
    "Safari_Zone_PA",
    "Save",
    "Shooting_Star",
    "Shrink",
    "Slots_New_Spin",
    "Slots_Reward",
    "Slots_Stop_Wheel",
    "Start_Menu",
    "Super_Effective",
    "Swap",
    "Switch",
    "Teleport_Enter1",
    "Teleport_Enter2",
    "Teleport_Exit1",
    "Teleport_Exit2",
    "Tink",
    "Trade_Machine",
    "Trainer_Appeared",
    "Turn_Off_PC",
    "Turn_On_PC",
    "Vine_Whip",
    "Withdraw_Deposit",
  },

  gold_sfx = {
    "Sfx_1stPlace",
    "Sfx_2Boops",
    "Sfx_2ndPlace",
    "Sfx_3rdPlace",
    "Sfx_Aeroblast",
    "Sfx_Attract",
    "Sfx_BallBounce",
    "Sfx_BallPoof",
    "Sfx_BallWobble",
    "Sfx_BatonPass",
    "Sfx_BeatUp",
    "Sfx_BellyDrum",
    "Sfx_Bind",
    "Sfx_Bite",
    "Sfx_Boat",
    "Sfx_BoneClub",
    "Sfx_BootPc",
    "Sfx_Bubblebeam",
    "Sfx_Bump",
    "Sfx_Burn",
    "Sfx_Call",
    "Sfx_CaughtMon",
    "Sfx_ChangeDexMode",
    "Sfx_Charge",
    "Sfx_ChooseACard",
    "Sfx_ChoosePcOption",
    "Sfx_CometPunch",
    "Sfx_Curse",
    "Sfx_Cut",
    "Sfx_Damage",
    "Sfx_DexFanfare140169",
    "Sfx_DexFanfare170199",
    "Sfx_DexFanfare200229",
    "Sfx_DexFanfare2049",
    "Sfx_DexFanfare230Plus",
    "Sfx_DexFanfare5079",
    "Sfx_DexFanfare80109",
    "Sfx_DexFanfareLessThan20",
    "Sfx_DoubleKick",
    "Sfx_Doubleslap",
    "Sfx_EggBomb",
    "Sfx_EggCrack",
    "Sfx_EggHatch",
    "Sfx_Elevator",
    "Sfx_ElevatorEnd",
    "Sfx_Ember",
    "Sfx_Encore",
    "Sfx_EnterDoor",
    "Sfx_EscapeRope",
    "Sfx_Evolved",
    "Sfx_ExitBuilding",
    "Sfx_ExpBar",
    "Sfx_Faint",
    "Sfx_Fanfare",
    "Sfx_Fanfare2",
    "Sfx_Flash",
    "Sfx_Fly",
    "Sfx_Foresight",
    "Sfx_FullHeal",
    "Sfx_GameFreakLogoGs",
    "Sfx_GetBadge",
    "Sfx_GetCoinFromSlots",
    "Sfx_GetEgg",
    "Sfx_GetTm",
    "Sfx_GetTrademon",
    "Sfx_GigaDrain",
    "Sfx_GiveTrademon",
    "Sfx_GotSafariBalls",
    "Sfx_GrassRustle",
    "Sfx_GsIntroCharizardFireball",
    "Sfx_GsIntroPokemonAppears",
    "Sfx_HangUp",
    "Sfx_Headbutt",
    "Sfx_HealBell",
    "Sfx_HitEndOfExpBar",
    "Sfx_HornAttack",
    "Sfx_HydroPump",
    "Sfx_HyperBeam",
    "Sfx_Item",
    "Sfx_JumpKick",
    "Sfx_JumpOverLedge",
    "Sfx_KarateChop",
    "Sfx_KeyItem",
    "Sfx_Kinesis",
    "Sfx_Kinesis2",
    "Sfx_Leer",
    "Sfx_LevelUp",
    "Sfx_Lick",
    "Sfx_MasterBall",
    "Sfx_MeanLook",
    "Sfx_MegaKick",
    "Sfx_MegaPunch",
    "Sfx_Menu",
    "Sfx_Metronome",
    "Sfx_MilkDrink",
    "Sfx_MindReader",
    "Sfx_Moonlight",
    "Sfx_MorningSun",
    "Sfx_MoveDeleted",
    "Sfx_MovePuzzlePiece",
    "Sfx_Nightmare",
    "Sfx_NoSignal",
    "Sfx_NotVeryEffective",
    "Sfx_Outrage",
    "Sfx_PayDay",
    "Sfx_Peck",
    "Sfx_PerishSong",
    "Sfx_PlacePuzzlePieceDown",
    "Sfx_Poison",
    "Sfx_PoisonSting",
    "Sfx_PokeballsPlacedOnTable",
    "Sfx_Pokeflute",
    "Sfx_Potion",
    "Sfx_Pound",
    "Sfx_Powder",
    "Sfx_Present",
    "Sfx_Protect",
    "Sfx_Psybeam",
    "Sfx_Psychic",
    "Sfx_PushButton",
    "Sfx_QuitSlots",
    "Sfx_Rage",
    "Sfx_RainDance",
    "Sfx_RazorWind",
    "Sfx_ReadText",
    "Sfx_ReadText2",
    "Sfx_RegisterPhoneNumber",
    "Sfx_Return",
    "Sfx_Run",
    "Sfx_Sandstorm",
    "Sfx_Save",
    "Sfx_Scratch",
    "Sfx_Screech",
    "Sfx_SecondPartOfItemfinder",
    "Sfx_Sharpen",
    "Sfx_Shine",
    "Sfx_ShutDownPc",
    "Sfx_Sing",
    "Sfx_Sketch",
    "Sfx_SlotMachineStart",
    "Sfx_SludgeBomb",
    "Sfx_Snore",
    "Sfx_Spark",
    "Sfx_SpiderWeb",
    "Sfx_Spite",
    "Sfx_Squeak",
    "Sfx_Stomp",
    "Sfx_StopSlot",
    "Sfx_Strength",
    "Sfx_Submission",
    "Sfx_SuperEffective",
    "Sfx_Supersonic",
    "Sfx_Surf",
    "Sfx_SweetKiss",
    "Sfx_SweetKiss2",
    "Sfx_SweetScent",
    "Sfx_SweetScent2",
    "Sfx_SwitchPockets",
    "Sfx_SwitchPokemon",
    "Sfx_SwordsDance",
    "Sfx_Tackle",
    "Sfx_TailWhip",
    "Sfx_Tally",
    "Sfx_Thief",
    "Sfx_Thief2",
    "Sfx_ThrowBall",
    "Sfx_Thunder",
    "Sfx_Thundershock",
    "Sfx_TitleScreenEntrance",
    "Sfx_Toxic",
    "Sfx_TrainArrived",
    "Sfx_Transaction",
    "Sfx_Unknown5F",
    "Sfx_Unknown60",
    "Sfx_Unknown61",
    "Sfx_Unknown63",
    "Sfx_Unknown66",
    "Sfx_Vicegrip",
    "Sfx_VineWhip",
    "Sfx_WallOpen",
    "Sfx_WarpFrom",
    "Sfx_WarpTo",
    "Sfx_WaterGun",
    "Sfx_Whirlwind",
    "Sfx_WingAttack",
    "Sfx_Wrong",
    "Sfx_ZapCannon",
  },

  gen1_species = {
    "ABRA",
    "AERODACTYL",
    "ALAKAZAM",
    "ARBOK",
    "ARCANINE",
    "ARTICUNO",
    "BEEDRILL",
    "BELLSPROUT",
    "BLASTOISE",
    "BULBASAUR",
    "BUTTERFREE",
    "CATERPIE",
    "CHANSEY",
    "CHARIZARD",
    "CHARMANDER",
    "CHARMELEON",
    "CLEFABLE",
    "CLEFAIRY",
    "CLOYSTER",
    "CUBONE",
    "DEWGONG",
    "DIGLETT",
    "DITTO",
    "DODRIO",
    "DODUO",
    "DRAGONAIR",
    "DRAGONITE",
    "DRATINI",
    "DROWZEE",
    "DUGTRIO",
    "EEVEE",
    "EKANS",
    "ELECTABUZZ",
    "ELECTRODE",
    "EXEGGCUTE",
    "EXEGGUTOR",
    "FARFETCHD",
    "FEAROW",
    "FLAREON",
    "GASTLY",
    "GENGAR",
    "GEODUDE",
    "GLOOM",
    "GOLBAT",
    "GOLDEEN",
    "GOLDUCK",
    "GOLEM",
    "GRAVELER",
    "GRIMER",
    "GROWLITHE",
    "GYARADOS",
    "HAUNTER",
    "HITMONCHAN",
    "HITMONLEE",
    "HORSEA",
    "HYPNO",
    "IVYSAUR",
    "JIGGLYPUFF",
    "JOLTEON",
    "JYNX",
    "KABUTO",
    "KABUTOPS",
    "KADABRA",
    "KAKUNA",
    "KANGASKHAN",
    "KINGLER",
    "KOFFING",
    "KRABBY",
    "LAPRAS",
    "LICKITUNG",
    "MACHAMP",
    "MACHOKE",
    "MACHOP",
    "MAGIKARP",
    "MAGMAR",
    "MAGNEMITE",
    "MAGNETON",
    "MANKEY",
    "MAROWAK",
    "MEOWTH",
    "METAPOD",
    "MEW",
    "MEWTWO",
    "MOLTRES",
    "MR_MIME",
    "MUK",
    "NIDOKING",
    "NIDOQUEEN",
    "NIDORAN_F",
    "NIDORAN_M",
    "NIDORINA",
    "NIDORINO",
    "NINETALES",
    "ODDISH",
    "OMANYTE",
    "OMASTAR",
    "ONIX",
    "PARAS",
    "PARASECT",
    "PERSIAN",
    "PIDGEOT",
    "PIDGEOTTO",
    "PIDGEY",
    "PIKACHU",
    "PINSIR",
    "POLIWAG",
    "POLIWHIRL",
    "POLIWRATH",
    "PONYTA",
    "PORYGON",
    "PRIMEAPE",
    "PSYDUCK",
    "RAICHU",
    "RAPIDASH",
    "RATICATE",
    "RATTATA",
    "RHYDON",
    "RHYHORN",
    "SANDSHREW",
    "SANDSLASH",
    "SCYTHER",
    "SEADRA",
    "SEAKING",
    "SEEL",
    "SHELLDER",
    "SLOWBRO",
    "SLOWPOKE",
    "SNORLAX",
    "SPEAROW",
    "SQUIRTLE",
    "STARMIE",
    "STARYU",
    "TANGELA",
    "TAUROS",
    "TENTACOOL",
    "TENTACRUEL",
    "VAPOREON",
    "VENOMOTH",
    "VENONAT",
    "VENUSAUR",
    "VICTREEBEL",
    "VILEPLUME",
    "VOLTORB",
    "VULPIX",
    "WARTORTLE",
    "WEEDLE",
    "WEEPINBELL",
    "WEEZING",
    "WIGGLYTUFF",
    "ZAPDOS",
    "ZUBAT",
  },

  gold_species = {
    "ABRA",
    "AERODACTYL",
    "AIPOM",
    "ALAKAZAM",
    "AMPHAROS",
    "ARBOK",
    "ARCANINE",
    "ARIADOS",
    "ARTICUNO",
    "AZUMARILL",
    "BAYLEEF",
    "BEEDRILL",
    "BELLOSSOM",
    "BELLSPROUT",
    "BLASTOISE",
    "BLISSEY",
    "BULBASAUR",
    "BUTTERFREE",
    "CATERPIE",
    "CELEBI",
    "CHANSEY",
    "CHARIZARD",
    "CHARMANDER",
    "CHARMELEON",
    "CHIKORITA",
    "CHINCHOU",
    "CLEFABLE",
    "CLEFAIRY",
    "CLEFFA",
    "CLOYSTER",
    "CORSOLA",
    "CROBAT",
    "CROCONAW",
    "CUBONE",
    "CYNDAQUIL",
    "DELIBIRD",
    "DEWGONG",
    "DIGLETT",
    "DITTO",
    "DODRIO",
    "DODUO",
    "DONPHAN",
    "DRAGONAIR",
    "DRAGONITE",
    "DRATINI",
    "DROWZEE",
    "DUGTRIO",
    "DUNSPARCE",
    "EEVEE",
    "EKANS",
    "ELECTABUZZ",
    "ELECTRODE",
    "ELEKID",
    "ENTEI",
    "ESPEON",
    "EXEGGCUTE",
    "EXEGGUTOR",
    "FARFETCH_D",
    "FEAROW",
    "FERALIGATR",
    "FLAAFFY",
    "FLAREON",
    "FORRETRESS",
    "FURRET",
    "GASTLY",
    "GENGAR",
    "GEODUDE",
    "GIRAFARIG",
    "GLIGAR",
    "GLOOM",
    "GOLBAT",
    "GOLDEEN",
    "GOLDUCK",
    "GOLEM",
    "GRANBULL",
    "GRAVELER",
    "GRIMER",
    "GROWLITHE",
    "GYARADOS",
    "HAUNTER",
    "HERACROSS",
    "HITMONCHAN",
    "HITMONLEE",
    "HITMONTOP",
    "HOOTHOOT",
    "HOPPIP",
    "HORSEA",
    "HOUNDOOM",
    "HOUNDOUR",
    "HO_OH",
    "HYPNO",
    "IGGLYBUFF",
    "IVYSAUR",
    "JIGGLYPUFF",
    "JOLTEON",
    "JUMPLUFF",
    "JYNX",
    "KABUTO",
    "KABUTOPS",
    "KADABRA",
    "KAKUNA",
    "KANGASKHAN",
    "KINGDRA",
    "KINGLER",
    "KOFFING",
    "KRABBY",
    "LANTURN",
    "LAPRAS",
    "LARVITAR",
    "LEDIAN",
    "LEDYBA",
    "LICKITUNG",
    "LUGIA",
    "MACHAMP",
    "MACHOKE",
    "MACHOP",
    "MAGBY",
    "MAGCARGO",
    "MAGIKARP",
    "MAGMAR",
    "MAGNEMITE",
    "MAGNETON",
    "MANKEY",
    "MANTINE",
    "MAREEP",
    "MARILL",
    "MAROWAK",
    "MEGANIUM",
    "MEOWTH",
    "METAPOD",
    "MEW",
    "MEWTWO",
    "MILTANK",
    "MISDREAVUS",
    "MOLTRES",
    "MR__MIME",
    "MUK",
    "MURKROW",
    "NATU",
    "NIDOKING",
    "NIDOQUEEN",
    "NIDORAN_F",
    "NIDORAN_M",
    "NIDORINA",
    "NIDORINO",
    "NINETALES",
    "NOCTOWL",
    "OCTILLERY",
    "ODDISH",
    "OMANYTE",
    "OMASTAR",
    "ONIX",
    "PARAS",
    "PARASECT",
    "PERSIAN",
    "PHANPY",
    "PICHU",
    "PIDGEOT",
    "PIDGEOTTO",
    "PIDGEY",
    "PIKACHU",
    "PILOSWINE",
    "PINECO",
    "PINSIR",
    "POLITOED",
    "POLIWAG",
    "POLIWHIRL",
    "POLIWRATH",
    "PONYTA",
    "PORYGON",
    "PORYGON2",
    "PRIMEAPE",
    "PSYDUCK",
    "PUPITAR",
    "QUAGSIRE",
    "QUILAVA",
    "QWILFISH",
    "RAICHU",
    "RAIKOU",
    "RAPIDASH",
    "RATICATE",
    "RATTATA",
    "REMORAID",
    "RHYDON",
    "RHYHORN",
    "SANDSHREW",
    "SANDSLASH",
    "SCIZOR",
    "SCYTHER",
    "SEADRA",
    "SEAKING",
    "SEEL",
    "SENTRET",
    "SHELLDER",
    "SHUCKLE",
    "SKARMORY",
    "SKIPLOOM",
    "SLOWBRO",
    "SLOWKING",
    "SLOWPOKE",
    "SLUGMA",
    "SMEARGLE",
    "SMOOCHUM",
    "SNEASEL",
    "SNORLAX",
    "SNUBBULL",
    "SPEAROW",
    "SPINARAK",
    "SQUIRTLE",
    "STANTLER",
    "STARMIE",
    "STARYU",
    "STEELIX",
    "SUDOWOODO",
    "SUICUNE",
    "SUNFLORA",
    "SUNKERN",
    "SWINUB",
    "TANGELA",
    "TAUROS",
    "TEDDIURSA",
    "TENTACOOL",
    "TENTACRUEL",
    "TOGEPI",
    "TOGETIC",
    "TOTODILE",
    "TYPHLOSION",
    "TYRANITAR",
    "TYROGUE",
    "UMBREON",
    "URSARING",
    "VAPOREON",
    "VENOMOTH",
    "VENONAT",
    "VENUSAUR",
    "VICTREEBEL",
    "VILEPLUME",
    "VOLTORB",
    "VULPIX",
    "WARTORTLE",
    "WEEDLE",
    "WEEPINBELL",
    "WEEZING",
    "WIGGLYTUFF",
    "WOBBUFFET",
    "WOOPER",
    "XATU",
    "YANMA",
    "ZAPDOS",
    "ZUBAT",
  },

  gen1_moves = {
    "POUND",
    "KARATE_CHOP",
    "DOUBLESLAP",
    "COMET_PUNCH",
    "MEGA_PUNCH",
    "PAY_DAY",
    "FIRE_PUNCH",
    "ICE_PUNCH",
    "THUNDERPUNCH",
    "SCRATCH",
    "VICEGRIP",
    "GUILLOTINE",
    "RAZOR_WIND",
    "SWORDS_DANCE",
    "CUT",
    "GUST",
    "WING_ATTACK",
    "WHIRLWIND",
    "FLY",
    "BIND",
    "SLAM",
    "VINE_WHIP",
    "STOMP",
    "DOUBLE_KICK",
    "MEGA_KICK",
    "JUMP_KICK",
    "ROLLING_KICK",
    "SAND_ATTACK",
    "HEADBUTT",
    "HORN_ATTACK",
    "FURY_ATTACK",
    "HORN_DRILL",
    "TACKLE",
    "BODY_SLAM",
    "WRAP",
    "TAKE_DOWN",
    "THRASH",
    "DOUBLE_EDGE",
    "TAIL_WHIP",
    "POISON_STING",
    "TWINEEDLE",
    "PIN_MISSILE",
    "LEER",
    "BITE",
    "GROWL",
    "ROAR",
    "SING",
    "SUPERSONIC",
    "SONICBOOM",
    "DISABLE",
    "ACID",
    "EMBER",
    "FLAMETHROWER",
    "MIST",
    "WATER_GUN",
    "HYDRO_PUMP",
    "SURF",
    "ICE_BEAM",
    "BLIZZARD",
    "PSYBEAM",
    "BUBBLEBEAM",
    "AURORA_BEAM",
    "HYPER_BEAM",
    "PECK",
    "DRILL_PECK",
    "SUBMISSION",
    "LOW_KICK",
    "COUNTER",
    "SEISMIC_TOSS",
    "STRENGTH",
    "ABSORB",
    "MEGA_DRAIN",
    "LEECH_SEED",
    "GROWTH",
    "RAZOR_LEAF",
    "SOLARBEAM",
    "POISONPOWDER",
    "STUN_SPORE",
    "SLEEP_POWDER",
    "PETAL_DANCE",
    "STRING_SHOT",
    "DRAGON_RAGE",
    "FIRE_SPIN",
    "THUNDERSHOCK",
    "THUNDERBOLT",
    "THUNDER_WAVE",
    "THUNDER",
    "ROCK_THROW",
    "EARTHQUAKE",
    "FISSURE",
    "DIG",
    "TOXIC",
    "CONFUSION",
    "PSYCHIC_M",
    "HYPNOSIS",
    "MEDITATE",
    "AGILITY",
    "QUICK_ATTACK",
    "RAGE",
    "TELEPORT",
    "NIGHT_SHADE",
    "MIMIC",
    "SCREECH",
    "DOUBLE_TEAM",
    "RECOVER",
    "HARDEN",
    "MINIMIZE",
    "SMOKESCREEN",
    "CONFUSE_RAY",
    "WITHDRAW",
    "DEFENSE_CURL",
    "BARRIER",
    "LIGHT_SCREEN",
    "HAZE",
    "REFLECT",
    "FOCUS_ENERGY",
    "BIDE",
    "METRONOME",
    "MIRROR_MOVE",
    "SELFDESTRUCT",
    "EGG_BOMB",
    "LICK",
    "SMOG",
    "SLUDGE",
    "BONE_CLUB",
    "FIRE_BLAST",
    "WATERFALL",
    "CLAMP",
    "SWIFT",
    "SKULL_BASH",
    "SPIKE_CANNON",
    "CONSTRICT",
    "AMNESIA",
    "KINESIS",
    "SOFTBOILED",
    "HI_JUMP_KICK",
    "GLARE",
    "DREAM_EATER",
    "POISON_GAS",
    "BARRAGE",
    "LEECH_LIFE",
    "LOVELY_KISS",
    "SKY_ATTACK",
    "TRANSFORM",
    "BUBBLE",
    "DIZZY_PUNCH",
    "SPORE",
    "FLASH",
    "PSYWAVE",
    "SPLASH",
    "ACID_ARMOR",
    "CRABHAMMER",
    "EXPLOSION",
    "FURY_SWIPES",
    "BONEMERANG",
    "REST",
    "ROCK_SLIDE",
    "HYPER_FANG",
    "SHARPEN",
    "CONVERSION",
    "TRI_ATTACK",
    "SUPER_FANG",
    "SLASH",
    "SUBSTITUTE",
    "STRUGGLE",
  },

  all_moves = {
    "POUND",
    "KARATE_CHOP",
    "DOUBLESLAP",
    "COMET_PUNCH",
    "MEGA_PUNCH",
    "PAY_DAY",
    "FIRE_PUNCH",
    "ICE_PUNCH",
    "THUNDERPUNCH",
    "SCRATCH",
    "VICEGRIP",
    "GUILLOTINE",
    "RAZOR_WIND",
    "SWORDS_DANCE",
    "CUT",
    "GUST",
    "WING_ATTACK",
    "WHIRLWIND",
    "FLY",
    "BIND",
    "SLAM",
    "VINE_WHIP",
    "STOMP",
    "DOUBLE_KICK",
    "MEGA_KICK",
    "JUMP_KICK",
    "ROLLING_KICK",
    "SAND_ATTACK",
    "HEADBUTT",
    "HORN_ATTACK",
    "FURY_ATTACK",
    "HORN_DRILL",
    "TACKLE",
    "BODY_SLAM",
    "WRAP",
    "TAKE_DOWN",
    "THRASH",
    "DOUBLE_EDGE",
    "TAIL_WHIP",
    "POISON_STING",
    "TWINEEDLE",
    "PIN_MISSILE",
    "LEER",
    "BITE",
    "GROWL",
    "ROAR",
    "SING",
    "SUPERSONIC",
    "SONICBOOM",
    "DISABLE",
    "ACID",
    "EMBER",
    "FLAMETHROWER",
    "MIST",
    "WATER_GUN",
    "HYDRO_PUMP",
    "SURF",
    "ICE_BEAM",
    "BLIZZARD",
    "PSYBEAM",
    "BUBBLEBEAM",
    "AURORA_BEAM",
    "HYPER_BEAM",
    "PECK",
    "DRILL_PECK",
    "SUBMISSION",
    "LOW_KICK",
    "COUNTER",
    "SEISMIC_TOSS",
    "STRENGTH",
    "ABSORB",
    "MEGA_DRAIN",
    "LEECH_SEED",
    "GROWTH",
    "RAZOR_LEAF",
    "SOLARBEAM",
    "POISONPOWDER",
    "STUN_SPORE",
    "SLEEP_POWDER",
    "PETAL_DANCE",
    "STRING_SHOT",
    "DRAGON_RAGE",
    "FIRE_SPIN",
    "THUNDERSHOCK",
    "THUNDERBOLT",
    "THUNDER_WAVE",
    "THUNDER",
    "ROCK_THROW",
    "EARTHQUAKE",
    "FISSURE",
    "DIG",
    "TOXIC",
    "CONFUSION",
    "PSYCHIC_M",
    "HYPNOSIS",
    "MEDITATE",
    "AGILITY",
    "QUICK_ATTACK",
    "RAGE",
    "TELEPORT",
    "NIGHT_SHADE",
    "MIMIC",
    "SCREECH",
    "DOUBLE_TEAM",
    "RECOVER",
    "HARDEN",
    "MINIMIZE",
    "SMOKESCREEN",
    "CONFUSE_RAY",
    "WITHDRAW",
    "DEFENSE_CURL",
    "BARRIER",
    "LIGHT_SCREEN",
    "HAZE",
    "REFLECT",
    "FOCUS_ENERGY",
    "BIDE",
    "METRONOME",
    "MIRROR_MOVE",
    "SELFDESTRUCT",
    "EGG_BOMB",
    "LICK",
    "SMOG",
    "SLUDGE",
    "BONE_CLUB",
    "FIRE_BLAST",
    "WATERFALL",
    "CLAMP",
    "SWIFT",
    "SKULL_BASH",
    "SPIKE_CANNON",
    "CONSTRICT",
    "AMNESIA",
    "KINESIS",
    "SOFTBOILED",
    "HI_JUMP_KICK",
    "GLARE",
    "DREAM_EATER",
    "POISON_GAS",
    "BARRAGE",
    "LEECH_LIFE",
    "LOVELY_KISS",
    "SKY_ATTACK",
    "TRANSFORM",
    "BUBBLE",
    "DIZZY_PUNCH",
    "SPORE",
    "FLASH",
    "PSYWAVE",
    "SPLASH",
    "ACID_ARMOR",
    "CRABHAMMER",
    "EXPLOSION",
    "FURY_SWIPES",
    "BONEMERANG",
    "REST",
    "ROCK_SLIDE",
    "HYPER_FANG",
    "SHARPEN",
    "CONVERSION",
    "TRI_ATTACK",
    "SUPER_FANG",
    "SLASH",
    "SUBSTITUTE",
    "STRUGGLE",
    "SKETCH",
    "TRIPLE_KICK",
    "THIEF",
    "SPIDER_WEB",
    "MIND_READER",
    "NIGHTMARE",
    "FLAME_WHEEL",
    "SNORE",
    "CURSE",
    "FLAIL",
    "CONVERSION2",
    "AEROBLAST",
    "COTTON_SPORE",
    "REVERSAL",
    "SPITE",
    "POWDER_SNOW",
    "PROTECT",
    "MACH_PUNCH",
    "SCARY_FACE",
    "FAINT_ATTACK",
    "SWEET_KISS",
    "BELLY_DRUM",
    "SLUDGE_BOMB",
    "MUD_SLAP",
    "OCTAZOOKA",
    "SPIKES",
    "ZAP_CANNON",
    "FORESIGHT",
    "DESTINY_BOND",
    "PERISH_SONG",
    "ICY_WIND",
    "DETECT",
    "BONE_RUSH",
    "LOCK_ON",
    "OUTRAGE",
    "SANDSTORM",
    "GIGA_DRAIN",
    "ENDURE",
    "CHARM",
    "ROLLOUT",
    "FALSE_SWIPE",
    "SWAGGER",
    "MILK_DRINK",
    "SPARK",
    "FURY_CUTTER",
    "STEEL_WING",
    "MEAN_LOOK",
    "ATTRACT",
    "SLEEP_TALK",
    "HEAL_BELL",
    "RETURN",
    "PRESENT",
    "FRUSTRATION",
    "SAFEGUARD",
    "PAIN_SPLIT",
    "SACRED_FIRE",
    "MAGNITUDE",
    "DYNAMICPUNCH",
    "MEGAHORN",
    "DRAGONBREATH",
    "BATON_PASS",
    "ENCORE",
    "PURSUIT",
    "RAPID_SPIN",
    "SWEET_SCENT",
    "IRON_TAIL",
    "METAL_CLAW",
    "VITAL_THROW",
    "MORNING_SUN",
    "SYNTHESIS",
    "MOONLIGHT",
    "HIDDEN_POWER",
    "CROSS_CHOP",
    "TWISTER",
    "RAIN_DANCE",
    "SUNNY_DAY",
    "CRUNCH",
    "MIRROR_COAT",
    "PSYCH_UP",
    "EXTREMESPEED",
    "ANCIENTPOWER",
    "SHADOW_BALL",
    "FUTURE_SIGHT",
    "ROCK_SMASH",
    "WHIRLPOOL",
    "BEAT_UP",
  },
}

  local playing = GameVersion.get()
  local isGen2 = GameVersion.generation(playing) == 2
  local generationName = isGen2 and "Gen 2 (Gold/Silver/Crystal)" or "Gen 1 (Red/Blue/Yellow)"

  -- These are the audio extensions decoded by the LÖVE 11.5 runtime bundled
  -- with Gen1Recomp 0.2.3: MP3, WAV, FLAC, Ogg Vorbis aliases, and libmodplug
  -- tracker/module formats. Ogg Opus still needs separate rejection below.
  local SUPPORTED_FORMATS = {
    mp3 = true,
    wav = true,
    flac = true,
    ogg = true,
    oga = true,
    ogv = true,

    ["699"] = true,
    abc = true,
    amf = true,
    ams = true,
    dbm = true,
    dmf = true,
    dsm = true,
    far = true,
    it = true,
    j2b = true,
    mdl = true,
    med = true,
    mid = true,
    mod = true,
    mt2 = true,
    mtm = true,
    okt = true,
    pat = true,
    psm = true,
    s3m = true,
    stm = true,
    ult = true,
    umx = true,
    xm = true,
  }
  local OGG_VORBIS_EXTENSIONS = {
    ogg = true,
    oga = true,
    ogv = true,
  }
  local MAX_RECOMMENDED_SFX_BYTES = 5 * 1024 * 1024
  -- Match Easy Custom Music v2’s generation-specific asset contract. The
  -- active game receives only its matching tree, so a player can supply
  -- distinct Gen 1 and Gen 2 replacements for the same friendly cue.
  local GENERATION_ROOT = isGen2 and "assets/Gen 2" or "assets/Gen 1"
  local GENERAL_ROOT = GENERATION_ROOT .. "/General Sound Effects"
  local SPECIFIC_ROOT = GENERATION_ROOT .. "/Specific Sound Effects"
  -- Pre-0.4 Sound Effect Replacer packages stored these at unlabelled roots.
  -- Keep a lower-priority one-release migration fallback so an update does not
  -- abruptly silence a user’s existing setup; the new generation tree wins.
  local LEGACY_GENERAL_ROOT = "assets/General Sound Effects"
  local LEGACY_SPECIFIC_ROOT = "assets/Specific Sound Effects"
  local migrationWarnings = {}
  local diagnostics, diagnosticSeen = {}, {}

  local function addDiagnostic(code, relative, detail)
    local key = code .. "|" .. relative
    if diagnosticSeen[key] then return end
    diagnosticSeen[key] = true
    diagnostics[#diagnostics + 1] = { code = code, relative = relative, detail = detail }
    mod.log:warn("%s: %s (%s).", code, relative, detail)
  end

  -- These friendly folders cover the normal things a player expects to change
  -- first. A more exact replacement is always available under Specific Sound
  -- Effects/Named Effects/<internal cue id>/.
  local GENERAL_REPLACEMENTS = {
    { folder = "Battle Damage",             gen1 = { "Damage" },                         gold = { "Sfx_Damage" } },
    { folder = "Battle Super Effective",    gen1 = { "Super_Effective" },                gold = { "Sfx_SuperEffective" } },
    { folder = "Battle Not Very Effective", gen1 = { "Not_Very_Effective" },             gold = { "Sfx_NotVeryEffective" } },
    { folder = "Battle Faint",              gen1 = { "Faint_Fall", "Faint_Thud" },      gold = { "Sfx_Faint" } },
    -- The shared Gen 2 catalog has no separately named trainer-encounter SFX.
    { folder = "Trainer Appeared",          gen1 = { "Trainer_Appeared" },                gold = {} },

    { folder = "Capture Throw",             gen1 = { "Ball_Toss" },                      gold = { "Sfx_ThrowBall" } },
    { folder = "Capture Success",           gen1 = { "Caught_Mon" },                     gold = { "Sfx_CaughtMon" } },
    { folder = "Capture Ball Bounce",       gen1 = {},                                   gold = { "Sfx_BallBounce" } },
    { folder = "Capture Ball Wobble",       gen1 = {},                                   gold = { "Sfx_BallWobble" } },
    { folder = "Level Up",                  gen1 = { "Level_Up" },                       gold = { "Sfx_LevelUp" } },

    { folder = "Item Received",             gen1 = { "Get_Item1", "Get_Item2" },        gold = { "Sfx_Item" } },
    { folder = "Key Item",                  gen1 = { "Get_Key_Item" },                   gold = { "Sfx_KeyItem" } },
    { folder = "Badge Received",            gen1 = { "Get_Item1" },                      gold = { "Sfx_GetBadge" } },
    { folder = "TM Received",               gen1 = { "Get_Item2" },                      gold = { "Sfx_GetTm" } },
    { folder = "Trade Complete",            gen1 = { "Trade_Machine" },                  gold = { "Sfx_GetTrademon", "Sfx_GiveTrademon" } },
    { folder = "Purchase",                  gen1 = { "Purchase" },                       gold = { "Sfx_Transaction" } },

    { folder = "Menu Open",                 gen1 = { "Start_Menu" },                     gold = { "Sfx_Menu" } },
    { folder = "Menu Confirm",              gen1 = { "Press_AB" },                       gold = { "Sfx_ReadText" } },
    { folder = "Menu Denied",               gen1 = { "Denied" },                         gold = { "Sfx_Wrong" } },
    { folder = "Save",                      gen1 = { "Save" },                           gold = { "Sfx_Save" } },
    { folder = "PC Boot",                   gen1 = { "Turn_On_PC" },                     gold = { "Sfx_BootPc" } },
    { folder = "PC Shutdown",               gen1 = { "Turn_Off_PC" },                    gold = { "Sfx_ShutDownPc" } },
    { folder = "Pokemon Switch",            gen1 = { "Swap", "Switch" },                gold = { "Sfx_SwitchPokemon" } },

    { folder = "Enter Building",            gen1 = { "Go_Inside" },                      gold = { "Sfx_EnterDoor" } },
    { folder = "Exit Building",             gen1 = { "Go_Outside" },                     gold = { "Sfx_ExitBuilding" } },
    { folder = "Warp",                      gen1 = { "Teleport_Enter1", "Teleport_Enter2", "Teleport_Exit1", "Teleport_Exit2" }, gold = { "Sfx_WarpFrom", "Sfx_WarpTo" } },
    { folder = "Run",                       gen1 = { "Run" },                            gold = { "Sfx_Run" } },
    { folder = "Jump Ledge",                gen1 = { "Ledge" },                          gold = { "Sfx_JumpOverLedge" } },
    { folder = "Cut Field Move",            gen1 = { "Cut" },                            gold = { "Sfx_Cut" } },
    { folder = "Fly Field Move",            gen1 = { "Fly" },                            gold = { "Sfx_Fly" } },
    { folder = "Strength Field Move",       gen1 = { "Push_Boulder" },                   gold = { "Sfx_Strength" } },

    { folder = "Heal HP",                   gen1 = { "Heal_HP" },                        gold = { "Sfx_Potion" } },
    { folder = "Heal Status",               gen1 = { "Heal_Ailment" },                   gold = { "Sfx_FullHeal" } },
    { folder = "Healing Machine",           gen1 = { "Healing_Machine" },                gold = {} },
    { folder = "Poison",                    gen1 = { "Poisoned" },                       gold = { "Sfx_Poison" } },
    { folder = "Pokedex Fanfare",           gen1 = { "Dex_Page_Added", "Pokedex_Rating" }, gold = { "Sfx_DexFanfareLessThan20", "Sfx_DexFanfare2049", "Sfx_DexFanfare5079", "Sfx_DexFanfare80109", "Sfx_DexFanfare140169", "Sfx_DexFanfare170199", "Sfx_DexFanfare200229", "Sfx_DexFanfare230Plus" } },
  }

  local function extension(name)
    return type(name) == "string" and name:match("^.+%.([^.]+)$")
  end

  -- The mod can inspect its own supplied bytes, but it deliberately does not
  -- attempt a full decoder preflight: the runtime owns that operation and some
  -- supported module formats do not have a single stable magic signature.
  -- These checks therefore catch only actionable, unambiguous setup mistakes.
  local function probeBytes(relative, info)
    if not info or not info.size or info.size > MAX_RECOMMENDED_SFX_BYTES then
      return nil
    end
    local ok, data = pcall(function() return mod:read(relative) end)
    if ok and type(data) == "string" then return data end
    return nil
  end

  local function headerProblem(normalizedExt, data)
    if not data then return nil end
    if OGG_VORBIS_EXTENSIONS[normalizedExt] then
      if data:sub(1, 4) ~= "OggS" then return "the file does not have an Ogg container header" end
      if data:find("OpusHead", 1, true) then return "Ogg Opus is unsupported; re-encode as Ogg Vorbis" end
    elseif normalizedExt == "wav" then
      if data:sub(1, 4) ~= "RIFF" or data:sub(9, 12) ~= "WAVE" then
        return "the file does not have a WAV header"
      end
    elseif normalizedExt == "flac" and data:sub(1, 4) ~= "fLaC" then
      return "the file does not have a FLAC header"
    end
    return nil
  end

  local function inspectReplacementFile(relative, name, info)
    if not name or name:sub(1, 1) == "." then return false end
    local ext = extension(name)
    local normalizedExt = ext and ext:lower()
    if not normalizedExt or not SUPPORTED_FORMATS[normalizedExt] then
      addDiagnostic("SFXR-A01", relative, "unsupported extension")
      return false
    end
    local problem = headerProblem(normalizedExt, probeBytes(relative, info))
    if problem then
      local code = problem:find("Opus", 1, true) and "SFXR-A02" or "SFXR-A03"
      addDiagnostic(code, relative, problem)
      return false
    end
    return true
  end

  local function compatibleFilesIn(relativeDir)
    -- The official validator deliberately provides a minimal mod object. A
    -- real game always exposes these asset methods; headless validation simply
    -- has no player files to scan.
    if type(mod.info) ~= "function" or type(mod.list) ~= "function" then return {} end
    local directory = mod:info(relativeDir)
    if not directory or directory.type ~= "directory" then return {} end
    local out, items = {}, mod:list(relativeDir) or {}
    table.sort(items)
    for _, name in ipairs(items) do
      local relative = relativeDir .. "/" .. name
      local info = mod:info(relative)
      if info and info.type == "file" and inspectReplacementFile(relative, name, info) then
        if info.size and info.size > MAX_RECOMMENDED_SFX_BYTES then
          mod.log:warn("Large static sound in %s: %s is %.1f MiB. Short files are recommended.", relativeDir, name, info.size / (1024 * 1024))
        end
        out[#out + 1] = { path = relative, name = name }
      end
    end
    return out
  end

  local function playlistFiles(root, legacyRoot, suffix)
    local preferred = compatibleFilesIn(root .. suffix)
    if #preferred > 0 then return preferred end
    local legacy = compatibleFilesIn(legacyRoot .. suffix)
    if #legacy > 0 then
      local key = legacyRoot .. suffix
      if not migrationWarnings[key] then
        migrationWarnings[key] = true
        mod.log:warn("Legacy Sound Effect Replacer path %s is in use. Move its files to %s for the Gen 1/Gen 2 layout.", legacyRoot .. suffix, root .. suffix)
      end
    end
    return legacy
  end

  local function asSet(values)
    local out = {}
    for _, value in ipairs(values or {}) do out[value] = true end
    return out
  end

  local activeNamedSfx = asSet(isGen2 and Catalog.gold_sfx or Catalog.gen1_sfx)
  local activeMoves = asSet(isGen2 and Catalog.all_moves or Catalog.gen1_moves)
  local activeSpecies = asSet(isGen2 and Catalog.gold_species or Catalog.gen1_species)

  -- Audio registries accept one definition per ID, so each file receives a
  -- private registered ID and a small router selects the next ID at playback.
  -- The cursor is process-owned rather than save-owned: it has no gameplay
  -- effect and intentionally resets when a mod reload replaces the playlist.
  local playlistCursor = Sound._sfxReplacerPlaylistCursor or {}
  Sound._sfxReplacerPlaylistCursor = playlistCursor
  local registrationSerial = 0

  local function nextPlaylist(ids, key)
    if not ids or #ids == 0 then return nil end
    local index = (playlistCursor[key] or 0) % #ids + 1
    playlistCursor[key] = index
    return ids[index]
  end

  local function registerSfxPlaylist(label, files)
    local ids = {}
    registrationSerial = registrationSerial + 1
    for index, file in ipairs(files) do
      local id = "SFX_SOUND_EFFECT_REPLACER_" .. label .. "_" .. registrationSerial .. "_" .. index
      mod.content.sfx:register(id, { file = mod.assets:path(file.path) })
      ids[#ids + 1] = id
    end
    return ids
  end

  local function registerCryPlaylist(label, files)
    local ids = {}
    registrationSerial = registrationSerial + 1
    for index, file in ipairs(files) do
      local id = "CRY_SOUND_EFFECT_REPLACER_" .. label .. "_" .. registrationSerial .. "_" .. index
      mod.content.cries:register(id, { file = mod.assets:path(file.path) })
      ids[#ids + 1] = id
    end
    return ids
  end

  local function registerMusicPlaylist(label, files)
    local ids = {}
    registrationSerial = registrationSerial + 1
    for index, file in ipairs(files) do
      local id = "Music_SOUND_EFFECT_REPLACER_" .. label .. "_" .. registrationSerial .. "_" .. index
      mod.content.music:register(id, { file = mod.assets:path(file.path) })
      ids[#ids + 1] = id
    end
    return ids
  end

  local sfxPlaylists, cryPlaylists, musicPlaylists = {}, {}, {}
  local function token(value) return tostring(value):gsub("[^%w_]", "_") end
  local generalFolders, generalCues, generalTracks = 0, 0, 0
  for _, replacement in ipairs(GENERAL_REPLACEMENTS) do
    local targets = isGen2 and replacement.gold or replacement.gen1
    if #targets > 0 then
      local files = playlistFiles(GENERAL_ROOT, LEGACY_GENERAL_ROOT, "/" .. replacement.folder)
      if #files > 0 then
        local playlist = registerSfxPlaylist("GENERAL_" .. token(replacement.folder), files)
        for _, id in ipairs(targets) do
          if activeNamedSfx[id] then
            sfxPlaylists[id] = playlist
            generalCues = generalCues + 1
          end
        end
        generalFolders, generalTracks = generalFolders + 1, generalTracks + #files
        mod.log:info("General Sound Effects: %s loaded %d file(s) for %s.", replacement.folder, #files, generationName)
      end
    end
  end

  -- Gen 2’s healing machine is a one-shot music jingle rather than an
  -- SFX. Route its playlist through the same public music-selection hook used
  -- by Easy Custom Music, without altering unrelated music choices.
  if isGen2 then
    local files = playlistFiles(GENERAL_ROOT, LEGACY_GENERAL_ROOT, "/Healing Machine")
    if #files > 0 then
      musicPlaylists.Music_HealPokemon = registerMusicPlaylist("HEALING_MACHINE", files)
      generalFolders, generalCues, generalTracks = generalFolders + 1, generalCues + 1, generalTracks + #files
      mod.log:info("General Sound Effects: Healing Machine loaded %d file(s) in Gen 2 (Gold/Silver/Crystal).", #files)
    end
  end

  -- Every named effect extracted by the current engine has an exact folder.
  -- Exact folders are installed after General Sound Effects and therefore win.
  local exactFolders, exactCues, exactTracks = 0, 0, 0
  for _, id in ipairs(isGen2 and Catalog.gold_sfx or Catalog.gen1_sfx) do
    local files = playlistFiles(SPECIFIC_ROOT, LEGACY_SPECIFIC_ROOT, "/Named Effects/" .. id)
    if #files > 0 then
      sfxPlaylists[id] = registerSfxPlaylist("EXACT_" .. token(id), files)
      exactFolders, exactCues, exactTracks = exactFolders + 1, exactCues + 1, exactTracks + #files
      mod.log:info("Named Effect %s loaded %d file(s) for %s.", id, #files, generationName)
    end
  end

  -- One generation-specific move folder per move ID. A playlist advances once
  -- per battle.move_used event, including Metronome and Mirror Move results.
  local moveSounds, moveFolders, moveTracks = {}, 0, 0
  for _, moveId in ipairs(Catalog.all_moves) do
    if activeMoves[moveId] then
      local files = playlistFiles(SPECIFIC_ROOT, LEGACY_SPECIFIC_ROOT, "/Move Sounds/" .. moveId)
      if #files > 0 then
        moveSounds[moveId] = registerSfxPlaylist("MOVE_" .. token(moveId), files)
        moveFolders, moveTracks = moveFolders + 1, moveTracks + #files
        mod.log:info("Move Sound %s loaded %d file(s) for %s.", moveId, #files, generationName)
      end
    end
  end

  if next(moveSounds) then
    mod.events:on("battle.move_used", function(event)
      local battle = event and event.battle
      local move = event and event.move
      local playlist = move and move.id and moveSounds[move.id]
      if not battle or not playlist then return end
      if type(battle.animationsOn) == "function" and not battle:animationsOn() then return end
      Sound.play(battle.data, nextPlaylist(playlist, "move:" .. move.id))
    end)
  end

  local cryFolders, cryCues, cryTracks = 0, 0, 0
  for _, species in ipairs(Catalog.gold_species) do
    if activeSpecies[species] then
      local files = playlistFiles(SPECIFIC_ROOT, LEGACY_SPECIFIC_ROOT, "/Pokemon Cries/" .. species)
      if #files > 0 then
        cryPlaylists[species] = registerCryPlaylist("CRY_" .. token(species), files)
        cryFolders, cryCues, cryTracks = cryFolders + 1, cryCues + 1, cryTracks + #files
        mod.log:info("Pokemon Cry %s loaded %d file(s) for %s.", species, #files, generationName)
      end
    end
  end

  -- Yellow’s PCM clips bypass the ordinary cry registry. Each numbered folder
  -- can still contain a playlist, while untouched clips retain native behavior.
  local pikaSounds, pikaFolders, pikaTracks = {}, 0, 0
  for index = 1, 42 do
    local clip = string.format("%02d", index)
    local files = playlistFiles(SPECIFIC_ROOT, LEGACY_SPECIFIC_ROOT, "/Yellow Pikachu Voice Clips/" .. clip)
    if #files > 0 then
      pikaSounds[index] = registerSfxPlaylist("PIKACHU_PCM_" .. clip, files)
      pikaFolders, pikaTracks = pikaFolders + 1, pikaTracks + #files
      mod.log:info("Yellow Pikachu voice clip %s loaded %d file(s).", clip, #files)
    end
  end

  -- Evolution progress is a music cue. Gen 2 reaches the active music playlist
  -- through music.select; Gen 1 selects a registered variant only for a real
  -- pending evolution, avoiding any unrelated map theme.
  local progressSounds, completeSounds
  local progressFiles = playlistFiles(SPECIFIC_ROOT, LEGACY_SPECIFIC_ROOT, "/Evolution/Evolution In Progress")
  if #progressFiles > 0 then
    progressSounds = registerMusicPlaylist("EVOLUTION_PROGRESS", progressFiles)
    if isGen2 then
      musicPlaylists.Music_Evolution = progressSounds
    else
      mod.hooks:wrap("evolution.check", function(next, game, mon, evo, trigger)
        local matched = next(game, mon, evo, trigger)
        if matched and game and game.data and game.data.audio then
          game.data.audio.special = game.data.audio.special or {}
          game.data.audio.special.evolution = nextPlaylist(progressSounds, "music:evolution_progress")
        end
        return matched
      end, 0)
    end
    mod.log:info("Evolution In Progress loaded %d file(s) in %s.", #progressFiles, generationName)
  end

  local completeFiles = playlistFiles(SPECIFIC_ROOT, LEGACY_SPECIFIC_ROOT, "/Evolution/Evolution Complete")
  if #completeFiles > 0 then
    completeSounds = registerSfxPlaylist("EVOLUTION_COMPLETE", completeFiles)
    if isGen2 then
      sfxPlaylists.Sfx_Evolved = completeSounds
    else
      mod.events:on("pokemon.evolved", function(event)
        if not (event and event.mon) then return end
        local ok, Game = pcall(require, "src.core.Game")
        local data = ok and Game and Game.data or nil
        if data then Sound.play(data, nextPlaylist(completeSounds, "sfx:evolution_complete")) end
      end)
    end
    mod.log:info("Evolution Complete loaded %d file(s) in %s.", #completeFiles, generationName)
  end

  -- `sfx` and `cries` deliberately have no built-in playlist record. Keep one
  -- narrow engine-internals bridge that changes only IDs owned by this mod;
  -- unassigned effects always call the native methods with their original ID.
  Sound._sfxReplacerPlaylists = { sfx = sfxPlaylists, cries = cryPlaylists, pika = pikaSounds }
  Sound._sfxReplacerSelect = function(kind, key)
    local group = Sound._sfxReplacerPlaylists and Sound._sfxReplacerPlaylists[kind]
    return nextPlaylist(group and group[key], kind .. ":" .. tostring(key))
  end
  Sound._sfxReplacerLast = Sound._sfxReplacerLast or { sfx = {} }

  if not Sound._sfxReplacerPlaylistWrapped and type(Sound.play) == "function" then
    Sound._sfxReplacerPlaylistWrapped = true
    local nativePlay, nativeStereo, nativeMove = Sound.play, Sound.playStereo, Sound.playMove
    local nativeCry, nativeStop, nativeIsPlaying = Sound.playCry, Sound.stop, Sound.isPlaying
    local function resolve(data, name)
      return type(Sound.resolve) == "function" and Sound.resolve(data, name) or name
    end
    local function routedSfx(data, name)
      local original = resolve(data, name)
      local selected = Sound._sfxReplacerSelect("sfx", original)
      if selected then
        Sound._sfxReplacerLast.sfx[original] = selected
        return selected
      end
      return nil
    end
    Sound.play = function(data, name)
      return nativePlay(data, routedSfx(data, name) or name)
    end
    if type(nativeStereo) == "function" then
      Sound.playStereo = function(data, name)
        return nativeStereo(data, routedSfx(data, name) or name)
      end
    end
    if type(nativeMove) == "function" then
      Sound.playMove = function(data, anim)
        local name = anim and anim.sound
        local selected = name and routedSfx(data, name)
        if not selected then return nativeMove(data, anim) end
        local replacement = {}
        for key, value in pairs(anim) do replacement[key] = value end
        replacement.sound = selected
        return nativeMove(data, replacement)
      end
    end
    if type(nativeCry) == "function" then
      Sound.playCry = function(data, species, pikaClip)
        local selected = Sound._sfxReplacerSelect("cries", species)
        return nativeCry(data, selected or species, pikaClip)
      end
    end
    if type(nativeStop) == "function" then
      Sound.stop = function(name)
        return nativeStop((Sound._sfxReplacerLast.sfx or {})[name] or name)
      end
    end
    if type(nativeIsPlaying) == "function" then
      Sound.isPlaying = function(name)
        return nativeIsPlaying((Sound._sfxReplacerLast.sfx or {})[name] or name)
      end
    end
  end

  -- The loader removes registered owners during hot reload, but direct Sound
  -- table changes survive. Keep one wrapper and replace only playlist state.
  Sound._sfxReplacerPikaSounds = pikaSounds
  if type(Sound.playPikaCry) == "function" and not Sound._sfxReplacerPikaWrapped then
    Sound._sfxReplacerPikaWrapped = true
    local nativePlayPikaCry = Sound.playPikaCry
    Sound.playPikaCry = function(data, index)
      index = math.max(1, math.min(42, tonumber(index) or 1))
      local selected = Sound._sfxReplacerSelect("pika", index)
      if selected then return Sound.play(data, selected) end
      return nativePlayPikaCry(data, index)
    end
  end

  if next(musicPlaylists) and mod.hooks and type(mod.hooks.wrap) == "function" then
    mod.hooks:wrap("music.select", function(next, song, context)
      local selected = next(song, context)
      return nextPlaylist(musicPlaylists[selected], "music:" .. tostring(selected)) or selected
    end)
  end

  if generalFolders + exactFolders + moveFolders + cryFolders == 0
      and not progressSounds and not completeSounds then
    mod.log:warn("No replacement audio found for %s. Add files under %s/General Sound Effects or %s/Specific Sound Effects, then restart.", generationName, GENERATION_ROOT, GENERATION_ROOT)
  else
    mod.log:info("Loaded %d general folders / %d cues / %d files, %d exact effects / %d files, %d move folders / %d files, %d cry folders / %d files, and %d Yellow voice folders / %d files for %s.", generalFolders, generalCues, generalTracks, exactCues, exactTracks, moveFolders, moveTracks, cryFolders, cryTracks, pikaFolders, pikaTracks, generationName)
  end

  -- A standard text box is intentionally deferred until the player has taken
  -- an overworld step. game.ready precedes title/intro flow, while world.stepped
  -- is emitted from the normal overworld step completion path. The message is
  -- advisory only: bad files have already been skipped, so it never suppresses
  -- a native cue or changes gameplay state beyond the ordinary textbox pause.
  if #diagnostics > 0 and mod.events and type(mod.events.on) == "function" then
    local warningShown = false
    mod.events:on("world.stepped", function()
      if warningShown then return end
      warningShown = true

      local game = mod.game
      if not (game and game.stack and type(game.stack.push) == "function") then
        mod.log:warn("SFXR-A04: Audio diagnostics were found, but the in-game text box could not be queued. Check the mod log.")
        return
      end
      local ok, TextBox = pcall(require, "src.render.TextBox")
      if not ok or not TextBox or type(TextBox.new) ~= "function" then
        mod.log:warn("SFXR-A04: Audio diagnostics were found, but the in-game text box is unavailable. Check the mod log.")
        return
      end

      local first = diagnostics[1]
      local count = #diagnostics
      local text = count == 1
        and ("SFX REPLACER:\n" .. first.code .. " FOUND.\nCHECK THE MOD LOG.")
        or ("SFX REPLACER:\n" .. count .. " AUDIO ISSUES.\nCHECK THE MOD LOG.")
      game.stack:push(TextBox.new(game, text))
      mod.log:info("SFXR diagnostic text box shown after first overworld step (%d issue(s)).", count)
    end)
  end

  -- PotatoVoxel is optional. The manifest's optional dependency makes its
  -- handle available here only when it is installed and enabled; Sound Effect
  -- Replacer remains fully usable when it is absent. The confirmation cue is
  -- authored in Lua through the supported ChipAsm API, so it has no external
  -- audio asset and cannot override any native game sound.
  local potatoVoxel = type(mod.find) == "function" and mod.find(POTATO_VOXEL_MOD_ID) or nil
  if potatoVoxel and mod.events and type(mod.events.on) == "function" then
    mod.content.sfx:register(POTATO_VOXEL_STARTUP_SFX, ChipAsm.sfx({
      -- A short original upward confirmation cue: approximately 728 Hz, then
      -- 904 Hz. The two notes total seven frames (about 117 ms) and use a fast
      -- decay to keep the result crisp and unobtrusive.
      engine = 1,
      channels = {
        {
          hw = 1,
          program = {
            { duty = 2 },
            { squareNote = { len = 3, volume = 15, fade = -7, frequency = 0x74C } },
            { squareNote = { len = 4, volume = 15, fade = -7, frequency = 0x76F } },
          },
        },
      },
    }))

    local potatoVoxelSoundPlayed = false
    mod.events:on("game.ready", function(event)
      if potatoVoxelSoundPlayed then return end
      local game = event and event.game
      local data = game and game.data
      if not data then return end
      potatoVoxelSoundPlayed = true
      if Sound.play(data, POTATO_VOXEL_STARTUP_SFX) then
        mod.log:info("PotatoVoxel detected; played Lua-authored startup confirmation sound.")
      else
        mod.log:warn("PotatoVoxel detected, but the Lua-authored startup confirmation sound could not be played.")
      end
    end)
  end
end
